### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by stachrom** [TimHeckel/meteor-fullcalendar#1]
Hi Tim

Can you point to a working example under meteor? 

regards roman

**Comment by TimHeckel** [comment]
Hi Roman. Sure -- here's what I do.

`mrt add fullcalendar` (of course)

```
Template.schedule_assessments.rendered = function () {
    $('#calendar').fullCalendar({
        weekends: false
        , defaultView: 'basicWeek'
    })
}
```

You have to instantiate the calendar during the `rendered` callback on your template.

**Comment by stachrom** [comment]
So far it's all clear.

My browser get somehow stuck... 
Could not locate the js files.

Magically everything is working now... :-) 

The missing js files are now in place. 

Thanks. 

roman
